### ISSUE TITLE
Unable to install on atom 1.7.3; Linux 4.4.0.22 Ubuntu (kubuntu) 16.04

### ISSUE THREAD

**Issue by eldrgeek** [Andifeind/atom-node-inspector#3]
Atom 1.7.3

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial

uname -a
Linux mwolf-ThinkPad-W520 4.4.0-22-generic #39-Ubuntu SMP Thu May 5 16:53:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```
installing “node-debug@0.1.1” failed.

> v8-debug@0.7.7 preinstall /tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-debug
> node -e 'process.exit(0)'


> v8-debug@0.7.7 install /tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

Unsupported target version: 0.36.8

> v8-profiler@5.6.5 preinstall /tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-profiler
> node -e 'process.exit(0)'


> v8-profiler@5.6.5 install /tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

Unsupported target version: 0.36.8

npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.36.8
node-pre-gyp ERR! stack     at get_runtime_abi (/tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/versioning.js:156:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/versioning.js:277:19)
node-pre-gyp ERR! stack     at install (/tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/lib/install.js:148:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:456:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:312:12)
node-pre-gyp ERR! System Linux 4.4.0-22-generic
node-pre-gyp ERR! command "node" "/tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v0.10.40
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.36.8
node-pre-gyp ERR! stack     at get_runtime_abi (/tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/lib/util/versioning.js:156:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/lib/util/versioning.js:277:19)
node-pre-gyp ERR! stack     at install (/tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/lib/install.js:148:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:456:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:312:12)
node-pre-gyp ERR! System Linux 4.4.0-22-generic
node-pre-gyp ERR! command "node" "/tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-profiler/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /tmp/apm-install-dir-116417-23256-10iwy6u/node_modules/node-debug/node_modules/node-inspector/node_modules/v8-profiler
node-pre-gyp ERR! node -v v0.10.40
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok 
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/mwolf/.atom/.apm/.apmrc" "--userconfig" "/home/mwolf/.atom/.apmrc" "install" "/tmp/d-116417-23256-vmq6j4/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116417-23256-10iwy6u/npm-debug.log
```

**Comment by crazytigershark** [comment]
Yes we now that problem. Atom uses a very old node version to install modules. It uses 0.10.40. This is OK for most of the node modules, but not for all. Some modules requires to be compiled against the v8 headers, like node-inspector, but node-inspector requires Node >= 4.x . We didn't found a solution to use the local installed Node version yet, but we're working on it.

**Comment by tnrich** [comment]
Any chance this will be fixed with the newest version of Atom?

**Comment by crazytigershark** [comment]
I pushed a new release. It'd worked for me on my Linux machine. Hope this helps :)
